name: run unit test

on:
  push:
    branches: [ main ]
    paths:
      - "csharp/chat-module-0.3/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.x' ]

    steps:
      # - uses: actions/cache@v3
      #   with:
      #     path: ~/.nuget/packages
      #     key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-nuget
      # - name: 의존성 설치
      #   run: dotnet add package Newtonsoft.Json --version 12.0.1
      - uses: actions/checkout@v3

      - name: 닷넷 설치 ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          

      - name: 파일 목록
        run: ls -al
        working-directory: csharp/chat-module-0.3/Tests
      

      - name: 의존성 설치
        run: |
          dotnet restore
          dotnet add package JunitXml.TestLogger --version 3.0.114
        working-directory: csharp/chat-module-0.3/Tests

      - name: 닷넷 버전 출력
        run: dotnet --version
          
      - name: 빌드
        run: dotnet build
        working-directory: csharp/chat-module-0.3/Tests

      - name: 테스트 실행
        run:  |
          dotnet test --logger:junit
          git status
        working-directory: csharp/chat-module-0.3/Tests

      - name: 테스트 결과 게시
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "${{ github.workspace }}/csharp/chat-module-0.3/Tests/TestResults/**/*.xml"
        

      - name: 변경 사항 출력 및 적용
        run: |
          git status
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "단위테스트 결과 업로드"
          git status
        working-directory: csharp/chat-module-0.3

      - name: 변경 사항 push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true