name: generate coverage badge

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.x' ]

    steps:
          
      # - uses: actions/cache@v3
      #   with:
      #     path: ~/.nuget/packages
      #     key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-nuget
      # - name: 의존성 설치
      #   run: dotnet add package Newtonsoft.Json --version 12.0.1
      
      - name: 경로 확인
        run: |
          cd ./csharp/chat-module-0.3
          ll
      
      - uses: actions/checkout@v3
      - name: 닷넷 설치 ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: 의존성 설치
          run: |
            dotnet restore
            dotnet add package JunitXml.TestLogger --version 3.0.114

      - name: 닷넷 버전 출력
        run: dotnet --version
          
      - name: 빌드
        run: dotnet build

      - name: 테스트 실행
          run: dotnet test --logger:"junit;LogFilePath=test-result.xml"

      - name: coverage 확인
        run: |
          coverage report
          coverage xml
          coverage html
          git status

      - name: 배지 생성
        run: |
          genbadge tests
          genbadge coverage -i - < coverage.xml
          git status

      - name: 변경 사항 출력 및 적용
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "변경 사항 적용"
          git status
          
      - name: 변경 사항 push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true